---
env:
  mocha: true
  node: true

extends:
  - airbnb-base

parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 2018
  babelOptions:
    configFile: ./config/babel.config-eslint.js

plugins:
  - chai-expect
  - chai-friendly
  - mocha-no-only
  - flowtype

rules:
  arrow-parens: 0
  class-methods-use-this: 0
  comma-dangle: 0
  consistent-return: 0
  curly: 0
  linebreak-style: 0
  lines-between-class-members: 0
  max-classes-per-file: 0
  max-len: 0
  no-await-in-loop: 0
  no-console:
    - warn
    - allow:
      - warn
      - error
  no-continue: 0
  no-mixed-operators: 0
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-restricted-syntax: 0
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  no-unused-expressions: 0
  nonblock-statement-body-position: 0
  object-curly-newline: 0
  prefer-destructuring: 0
  spaced-comment: 0

  chai-expect/missing-assertion: 2
  chai-expect/terminating-properties: 1

  chai-friendly/no-unused-expressions: 2

  flowtype/boolean-style:
    - error
    - bool
  flowtype/define-flow-type: 1
  flowtype/delimiter-dangle: 0
  flowtype/generic-spacing:
    - error
    - never
  flowtype/no-mixed: 0
  flowtype/no-primitive-constructor-types: 2
  flowtype/no-types-missing-file-annotation: 2
  flowtype/no-weak-types: 0
  flowtype/require-parameter-type: 0
  flowtype/require-return-type: 0
  flowtype/require-valid-file-annotation:
    - error
    - always
  flowtype/semi: 2
  flowtype/space-after-type-colon:
    - error
    - always
  flowtype/space-before-generic-bracket:
    - error
    - never
  flowtype/space-before-type-colon:
    - error
    - never
  flowtype/type-id-match: 0
  flowtype/union-intersection-spacing:
    - error
    - always

  import/no-named-as-default: 0
  import/prefer-default-export: 0

  mocha-no-only/mocha-no-only:
    - error
